# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = '($character)'
right_format = '''$git_branch$git_status$directory'''

add_newline = false
command_timeout = 5000

[line_break]
disabled = true

[cmd_duration]
min_time = 500
format = 'underwent [$duration](bold yellow)'

[nodejs]
symbol = '⬢ '

[lua]
symbol = ' '

[golang]
symbol = ' '

[git_branch]
symbol = ' '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['master', 'main']

[directory]
truncation_length = 1
truncation_symbol = '…/'
# home_symbol = '󱎃'
read_only = '  '

[git_status]
format= "[ 󰊤 ](green)[$all_status$ahead_behind](green) "
conflicted = "="
ahead =	" 󰄿 ${count}"
behind = " 󰄼 ${count}"
diverged = " 󰄿 ${ahead_count} 󰄼 ${behind_count}"
up_to_date = " 󰄬"
untracked = "?${count}"
stashed = "󰏖"
modified = "!${count}"
staged = "+${count}"
renamed = "*${count}"
deleted = "-${count}"
